
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("Dummy6.Resource", IsApplication=true)>]
    do ()

namespace XaOpenXC
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnException337f05e38dce4e4c988a62684df939aa of obj
    exception ReturnNoneException337f05e38dce4e4c988a62684df939aa
    [<AutoOpen>]
    module FuncConvertFinalOverload337f05e38dce4e4c988a62684df939aa =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                ()


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member Icon = 2130837504
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f060003
            static member btnClear = 2131099651
            
            // aapt resource value: 0x7f060002
            static member btnRefresh = 2131099650
            
            // aapt resource value: 0x7f060005
            static member btnStartService = 2131099653
            
            // aapt resource value: 0x7f060006
            static member btnStopService = 2131099654
            
            // aapt resource value: 0x7f060008
            static member btnViewLog = 2131099656
            
            // aapt resource value: 0x7f060007
            static member btnViewMessages = 2131099655
            
            // aapt resource value: 0x7f060000
            static member linearLayout1 = 2131099648
            
            // aapt resource value: 0x7f060001
            static member linearLayout2 = 2131099649
            
            // aapt resource value: 0x7f060004
            static member textView1 = 2131099652
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member Log = 2130903040
            
            // aapt resource value: 0x7f030001
            static member Main = 2130903041
            
            // aapt resource value: 0x7f030002
            static member Messages = 2130903042
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050001
            static member app_name = 2131034113
            
            // aapt resource value: 0x7f050000
            static member hello = 2131034112
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Xml () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040000
            static member device_filter = 2130968576
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

